### ISSUE TITLE
No stairs in creative inventory

### ISSUE THREAD

**Issue by sbrl** [minetest-mods/moreblocks#119]
Upon installing this mod, almost all the stairs in the creative inventory have disappeared! Worse still, if   remove it, all the stairs & slabs in my existing build get corrupted.

What can I do?

**Comment by sbrl** [comment]
I've solved the issue by reverting to a backup. Perhaps some attention should be given to allowing creative builders easier access to stairs & slabs?

**Comment by sbrl** [comment]
@daufinsyd I took a backup of my world before I installed the mod. I simply restored it and deleted the mod.

**Comment by daufinsyd** [comment]
Ok thanks :)
