### ISSUE TITLE
auto-rotation of default:*wood blocks

### ISSUE THREAD

**Issue by thomasrudin** [minetest-mods/moreblocks#123]
When i place some stairs or slopes the blocks auto-rotate in one direction only. No matter from which direction i place them.

The moretrees:* wood placement is fine, only the default:* wood is affected.

Minetest (engine/game) version: 0.4.17.1 (0.4-backport)
Moreblocks version: 10dd84a7f190204f713dd551ec3b3d17cef7d959

Other mods:
* Technic
* Moretrees

**Comment by Calinou** [comment]
I can reproduce this in 0.4.17.1. #123 contained a fix, but it's said to be problematic with 0.5-dev. Should I still merge it anyway?

**Comment by thomasrudin** [comment]
The fix : https://github.com/sys4-fr/moreblocks/commit/3cbc708742585154ce5e7490457fbc831ca1245a works for me, but there seems to be an existing root cause.
How do you handle engine-versions vs. mod-versions in this repo?
Maybe merge it in a 0.4.17.1 feature branch

**Comment by VanessaE** [comment]
I can reproduce this with only Moreblocks loaded (no other mods).

Minetest engine is on the stable-0.4 branch, commit https://github.com/minetest/minetest/commit/dd5f03731ad545f52da24825a2ee870f899f6adc, minetest_game on the stable-0.4 branch, commit https://github.com/minetest/minetest_game/commit/d6a66860af6fc39957d8e947824b9c56c3686b8e, moreblocks at commit 723db44933721cc14e85ec40ada5ae5e936cb7d7

**Comment by VanessaE** [comment]
:tada:
