### ISSUE TITLE
stairsplus items hidden in creative inventory

### ISSUE THREAD

**Issue by daufinsyd** [minetest-mods/moreblocks#125]
All the stairsplus items are hidden in the inventory (I found the following line in **config.lua** )

> -- Show stairs/slabs/panels/microblocks in creative inventory (true or false):
> setting("bool", "stairsplus_in_creative_inventory", false)

Is there any specific reason for hidding it ? It's a pain to build in creative mode without stairs, slabs ... already crafted. Otherwise it would be great to turn this to true.

Edit : related #119

**Comment by sbrl** [comment]
Perhaps a slash command would work to configure it?

**Comment by daufinsyd** [comment]
Actually it displays all stairsplus items (not only stairs and slabs)

**Comment by Linuxdirk** [comment]
I was about to open an issue for the same reason. Pretty annoying actually. I wish the mod would not mess with the normal stairs.

related (for "don't mess with stairs" statement): https://github.com/minetest-mods/moreblocks/issues/139 https://github.com/minetest-mods/moreblocks/issues/138

**Comment by Calinou** [comment]
Stairs+ nodes were hidden because they take up a lot of space in the creative inventory, which made it more difficult to browse.

**Comment by Linuxdirk** [comment]
In my opinion the best would be not hiding the `stairs` mod stairs but only your own objects. Having to use the saw in creative to just get some normal stairs is not the best way.

**Comment by sbrl** [comment]
Yeah, this is actually a deal-breaker for me. I do use the  search to find the right sort of node that I'm looking for in the creative _Unified Inventory_ anyway, so it would be nice to display the stairs in the search interface for this reason.
