### ISSUE TITLE
Placement of default stairs is messed up

### ISSUE THREAD

**Issue by ghost** [minetest-mods/moreblocks#138]
* Minetest 5.0.0
* Moreblocks 936306803bc45ddb19c7594e85ff5184452e9ad0

When placing stairs nodes (slabs and outer/inner/normal stairs from the `stairs` mod that comes with *Minetest Game*) they’re all illogically rotated ignoring the position they’re placed on.

The following two screenshots show the wooden stairs nodes placed against the stone node behind them always alternating between placing against lower half and upper half of the node.

![placement_default](https://user-images.githubusercontent.com/46120351/54480715-22232400-482c-11e9-89b5-c77d7e5f7af6.png)

Below I did the same with moreblocks enabled.

![placement_moreblocks](https://user-images.githubusercontent.com/46120351/54480716-22232400-482c-11e9-91d1-af4fe7e88834.png)

It seems like the stair nodes now ignore the placement and are just placed sideways.

**Comment by Oblomov** [comment]
I have implemented a logic similar to the MTG one in PR#160. It is enabled when placing pressing the aux key (E, by default).

I have tested it with slabs and I'm satisfied with the result, but there may be cases I missed (esp. place under block case), so I would appreciate if you have the opportunity to test it.

**Comment by Oblomov** [comment]
A revised version of my PR got merged in 2.1.0, could you please check if stairs placement is now to your satisfaction?

**Comment by Calinou** [comment]
OP removed their account (which is why it appears as @ghost), so I'll close this issue.
