### ISSUE TITLE
Server crashes with “Malformatted inventory list” error when started in creative mode

### ISSUE THREAD

**Issue by ghost** [minetest-mods/moreblocks#141]
**Versions**
* Minetest 5.0.0
* moreblocks on d96f110821f91efa45a2454118454ea32efe1431

**What happens?**

The server crashes with the following message when started in creative mode.

```
2019-03-29 19:29:11: ERROR[Main]: A serialization error occurred:
2019-03-29 19:29:11: ERROR[Main]: Malformatted inventory list. list=main, read 1435 of 4692 ItemStacks.
2019-03-29 19:29:11: ERROR[Main]: The server is probably  running a different version of Minetest.
```

**Reproduce crash**
* Start Minetest 5.0.0
* Create a new world
* Enable creative mode
* Enable `moreblocks` mod
* Start the world
* -> The server crashes

**Verify that it only happens in creative mode**
* Do the same
* Disable creative mode
* Start the world
* -> Server does not crash

**Comment by Calinou** [comment]
Does this occur if you set `moreblocks.stairs_in_creative_inventory = false` in `minetest.conf`? (See [config.lua](https://github.com/minetest-mods/moreblocks/blob/master/config.lua#L29).)

**Comment by Linuxdirk** [comment]
No, with this set the server starts as expected (actually it even starts a little faster and does not “pause” for a second during loading stage).

**Comment by Calinou** [comment]
Looks like I'll have to revert that setting to `false` by default then. :disappointed:

**Comment by Linuxdirk** [comment]
Do you have any idea what the issue could be? In older versions of one of my mods I was able to add multiple thousands of nodes to the creative inventory. The inventory itself should be absolutely capable of having `moreblocks` nodes for all `defualt` nodes added.

**Comment by Calinou** [comment]
@Linuxdirk Sorry, I don't know why this happens.
