### ISSUE TITLE
Migrate translations to the Minetest localization format

### ISSUE THREAD

**Issue by Calinou** [minetest-mods/moreblocks#149]
We should migrate the translations to the [Minetest localization format](https://rubenwardy.com/minetest_modding_book/lua_api.html#translations), so that we can benefit from client-side translations.

If anyone has spare time, feel free to open a pull request :slightly_smiling_face:

**Comment by Panquesito7** [comment]
I believe this issue can be closed. I think it has been fixed.

**Comment by Calinou** [comment]
Indeed, this was implemented by https://github.com/minetest-mods/moreblocks/pull/186.
