### ISSUE TITLE
Glass slopes and microblocks, minor issues

### ISSUE THREAD

**Issue by baryluk** [minetest-mods/moreblocks#152]
![screenshot_20200413_051840](https://user-images.githubusercontent.com/110322/79094279-89b8e500-7d46-11ea-8f5a-c33f5d74f055.png)

I really like the slopes, but there are few issues. The upper side edges are missing, and it lower edges doesn't blend with other blocks, when continues glass is enabled in minetest.

**Comment by Calinou** [comment]
> The upper side edges are missing, and it lower edges doesn't blend with other blocks, when continues glass is enabled in minetest.

I'm afraid I can't fix that. Connected glass only works for nodes of the same drawtype; it can't connect textures from nodes with different drawtypes.
