### ISSUE TITLE
Request for new block types / geometries, shelf-like

### ISSUE THREAD

**Issue by baryluk** [minetest-mods/moreblocks#154]
I am doing quite a bit of architectural modeling and concepts in minetest, and I would like more abilities to model shelves, for books, storage, etc, In general I love shelves in real life too.

Here are proposed blocks in 1:16 scale:

![screenshot_20200420_140754](https://user-images.githubusercontent.com/110322/79769156-4ac4f980-831b-11ea-80c1-8342dae64f54.png)
![screenshot_20200420_152424](https://user-images.githubusercontent.com/110322/79769525-c4f57e00-831b-11ea-97f2-ab351f009932.png)
![screenshot_20200420_152203](https://user-images.githubusercontent.com/110322/79769484-b313db00-831b-11ea-86fd-21a3c576f529.png)

![screenshot_20200420_141357](https://user-images.githubusercontent.com/110322/79769225-5c0e0600-831b-11ea-88a7-493c98758c72.png)
![screenshot_20200420_150043](https://user-images.githubusercontent.com/110322/79769406-97103980-831b-11ea-983d-5f50349a310e.png)

![screenshot_20200420_145441](https://user-images.githubusercontent.com/110322/79769289-721bc680-831b-11ea-9fb1-0638b6f07f30.png)
![screenshot_20200420_145734](https://user-images.githubusercontent.com/110322/79769332-819b0f80-831b-11ea-835e-3c2a05b698a3.png)
![screenshot_20200420_151515](https://user-images.githubusercontent.com/110322/79769449-a4c5bf00-831b-11ea-8376-ba4bdb965727.png)

The 16x16 stone base, is just for my reference and is not a part of the block. It should be clear.

These can be chained to create bigger shelves on walls, and from ground up. They can be also mixed between each other, or stacked for bigger height, or turned on a side, and connected in various ways. Some of the above blocks also work well with existing blocks from moreblocks, like 3-sided U-type microblock / slab.

As of the textures, I am mostly interested in woods, and with horizontal grain. But more the merrier. Could be fully orthogonal.

There are few more geometries I would like too, but these are the ones I would probably use the most.

**Comment by Calinou** [comment]
I'd rather leave "detailed" blocks up to other mods to implement. Since we already have a lot of different blocks defined, I'd rather not add even more and slow down loading times. Sorry :slightly_frowning_face:
