### ISSUE TITLE
Drag Drop decreases Input material but does not increase output material when dropped on existing pile

### ISSUE THREAD

**Issue by Bastrabun** [minetest-mods/moreblocks#157]
Minetest 5.3.0 on debian 10: I can drag a result shape to my inventory and drop it onto an already existing pile. The material needed gets deducted from the "input material" slot, although nothing is added to my inventory. Repro goes like this:

1. Place saw
2. Insert 99 woodplank into Input material slot
3. Click once on the slab 1/16 (row2, line3)
=> Cursor shows the 1/16 planks, Input material not changed
4. Click once on a free slot in your inventory
=> Cursor shows nothing, Input material changes to 86 woodplank (+5 microblocks)
=> Everything ok until now
5. Click again once on the slab 1/16 (row2, line3)
=> Cursor shows the 1/16 planks, Input material not changed
6. Click once on the already existing pile of 1/16 slabs in your inventory
=> Cursor still shows the 1/16 planks, Input material decreased to 74 woodplanks (+2 microblocks)

You can repeat step 6 until the Input material slot is empty and all you got from it was a 99 stack of 1/16 woodplanks

**Comment by OgelGames** [comment]
Not reproducible in MT 5.4.0, most likely fixed by https://github.com/minetest/minetest/commit/051e4c2b00a30c496b5545a6f0b01c9a14e937a4

**Comment by Calinou** [comment]
Closing per @OgelGames'
 comment.
