### ISSUE TITLE
New stairs placement doesn't work correctly when placing onto `buildable_to` nodes

### ISSUE THREAD

**Issue by OgelGames** [minetest-mods/moreblocks#164]
See https://github.com/minetest-mods/moreblocks/pull/160#issuecomment-747895840

**Comment by Oblomov** [comment]
I'm not entirely sure this is  about `buildable_to`, but I'm observing this when placing over half-size blocks. I suspect this is related to `pointed_thing_to_face_pos` failing in this case. Let me see if I can improve on this.

**Comment by Oblomov** [comment]
This should be fixed in #166, but I would appreciate it if @OgelGames or @BuckarooBanzay could test it to verify that it indeed fixes the issue for them.

**Comment by OgelGames** [comment]
Yep, that fixes it, thanks 👍
