### ISSUE TITLE
slope placement with non-default nodes results in strange behavior

### ISSUE THREAD

**Issue by BuckarooBanzay** [minetest-mods/moreblocks#167]
When i'm placing slope nodes from the `scifi_nodes` mod (github.com/D00Med/scifi_nodes/)
i get some weird placement issues:

![screenshot_20201218_174631](https://user-images.githubusercontent.com/39065740/102639375-41fe1f00-4159-11eb-861a-4ee59e65c4dc.png)

Regardless of player position

Possbly related to: https://github.com/minetest-mods/moreblocks/pull/160

**Comment by Oblomov** [comment]
LOL OK, I see why this is happening: the mod has a `_` in its name, which is busting my “same category” detection code. I think this should be relatively easy to fix. Let me give it a roll.

**Comment by Oblomov** [comment]
@BuckarooBanzay can you please test #168 ? I would appreciate if you could verify two things: one is that you don't get the weird placement that you see now, and the other is that you should get the “optimized placement for same category” even across mods (e.g. default slope against `scifi_nodes` slope).
