### ISSUE TITLE
Crash when recycling default stairs

### ISSUE THREAD

**Issue by Caellian** [minetest-mods/moreblocks#174]
## Steps to reproduce:
- Open a world without moreblocks enabled
- Craft stairs
- Enable moreblocks
- Insert input material for previously crafted stairs
- Put previously crafted (default) stairs into recycle slot
- Crash on line `circular_saw.lua:261` bc cost is `nil`

## What I believe is happening:
Due to alias definition, contains_item returns true for default stairs, but get_cost does not take aliases into consideration and returns nil.

This happened with acacia stairs, but is likely a problem with all aliased nodes.

Adding
```lua
if not cost then
  return 0
end 
```
before line 261 (`if (incost + cost) > maxcost then` in `circular_saw.allow_metadata_inventory_put`) prevents crash from occurring, but a better approach would be to keep track of aliased nodes in `aliases.lua` try mapping old node into a new one to consistently calculate cost.

**Comment by Calinou** [comment]
> Adding
>
> ```lua
> if not cost then
>     return 0
> end 
>
> before line 261 (`if (incost + cost) > maxcost then` in `circular_saw.allow_metadata_inventory_put`) prevents crash from occurring, but a better approach would be to keep track of aliased nodes in `aliases.lua` try mapping old node into a new one to consistently calculate cost.

Maybe we should return an extremely high cost in this case? We should avoid introducing a duplication bug while fixing this 🙂

**Comment by Caellian** [comment]
> Maybe we should return an extremely high cost in this case? We should avoid introducing a duplication bug while fixing this slightly_smiling_face

Returning 0 prevents the item from being inserted.

I suggested using aliases instead as it would result in expected behaviour instead of preventing players from recycling default stairs which might be confusing if they don't know what's going on.
