### ISSUE TITLE
Broken crafting recipe

### ISSUE THREAD

**Issue by axcore** [minetest-mods/moreblocks#185]
crafting.lua, line 557

Is
`	output = "moreblocks:cactuschecker 4",`

Should be
`	output = "moreblocks:cactus_checker 4",`

**Comment by Calinou** [comment]
Both crafting recipes appear to work, since `moreblocks:cactuschecker` is aliased to `moreblocks:cactus_checker`. Nonetheless, I'll still fix the typo.
