### ISSUE TITLE
Some blocks are not sawable?

### ISSUE THREAD

**Issue by mwrsa** [minetest-mods/moreblocks#20]
I only noted wool and metal blocks so far, but they at least are not compatible with the table saw. Would be nice to get that fixed, along with others I may not yet have found out! Thanks.

**Comment by Calinou** [comment]
Wool being sawable would greatly increase the number of nodes to create (since there are 16 colors), which would increase the game startup time.

**Comment by t4im** [comment]
With metals he probably meant moreore metals. While rather belonging added there, not here, they keep coming up for me quite often too. Especially on technic games this becomes quite obvious, when basicly all metals end up being sawable, but Tin and Silver.

**Comment by sofar** [comment]
@Calinou can we close this? I think we don't want wool to be sawable for now, and the missing ores is something likely better coded in moreores.

Keeping this issue open here suggests that this is still being considered, which I don't think it is?

**Comment by deezl** [comment]
just a quick note: adding the gloopblocks mod makes wool sawable.
