### ISSUE TITLE
Big issue on Multicraft, Downloading MoreBlocks pack adds +100 slopes from Circular Saw

### ISSUE THREAD

**Issue by NerdyFreezeboyUnknownguy** [minetest-mods/moreblocks#202]
this is the whole message:

“Failed to load and run script from /private/var/mobile/Containers/Data/Application/0529E8C0-2299-4951-A248-2660E9455522/Documents/mods/moreblocks/init.lua:
...2F38F5E3/MultiCraft.app//builtin/common/misc_helpers.lua:488: table index is nil
stack traceback:
	...2F38F5E3/MultiCraft.app//builtin/common/misc_helpers.lua:488: in function 'copy'
	...2/Documents/mods/moreblocks/stairsplus/registrations.lua:108: in main chunk
	[C]: in function 'dofile'
	...60E9455522/Documents/mods/moreblocks/stairsplus/init.lua:82: in main chunk
	[C]: in function 'dofile'
	...951-A248-2660E9455522/Documents/mods/moreblocks/init.lua:20: in main chunk
Revisa debug.txt para más detalles.”

![IMG_1592](https://github.com/minetest-mods/moreblocks/assets/154117541/d1e91d4e-ba2c-4e0c-88e2-efa4d1ad9c1e)

**Comment by NerdyFreezeboyUnknownguy** [comment]
Hello, I use Multicraft to Join BlockCity Server.
Recently I tried to do my own one player server with Minetest on the Multicraft App
I downloaded a bunch of Mods who work just perfect
The More Blocks Mod also works correctly, the issue is when I try to activate all of the downloaded stuff including the More Blocks, the map won’t load and this message from the image above appears.
I’m sorry about my english, I don’t know nothing about programming, and im from Mexico, I just wanted to ask for help.
I use the circular saw a lot, and I don’t see why if I’m downloading that pack, then why am I getting all the possible blocks from the circular saw to fill my inventory, I see this as a big issue.
When I load a new map adding only the MoreBlocks pack the map will load just great, but my inventory gets filled with all of the possible blocks from the circular saw.
I only need the blocks, not the already cut ones. (That’s why I have the circular saw)
But when I Load a map with More Blocks + other Mods the map won’t load
I hope I’m making myself clear, I’ll upload more images if needed.
Just erase the rest of the already cut ones from the inventory
Thanks for reading.

**Comment by Calinou** [comment]
This is expected, and is done by default so you can use these nodes without having to place a circular saw every time (it would get annoying over time).

https://github.com/minetest-mods/moreblocks/issues/144 is a better solution to the problem described here, so I'll close this in favor of that issue.

**Comment by NerdyFreezeboyUnknownguy** [comment]
Hello Hugo, thanks for the reply
I asked someone (wsor) for help and told me this Is a setting and I can
change It to use only the circular saw, the problem Is this setting can
only be disabled on PC (for what I understood
Im using iPad and there Is no way to disable this setting.)
Besides
I dont understand why would It be an issue to place the circular saw each
Time someone needs to use it, I would prefer to place 10 of them instead of
go through +150 Pages just to find one particular slope, stair, etcétera.
I hope, anyways, if maybe you or someone can do something, specifically for
Mobile device players, in order to Fix this, because It Is a real issue, we
have to decide between downloading More Blocks & nothing else or download
any quantity of packs except for More Blocks.

-Maybe you or someone can increase the memory of LUAscript for Mobile
devices (for what I understood this Is the issue in order to run this pack
with all others)

-Maybe add a way to able/disable this from the inventory, for the Users
that prefer to display the circular saw and dont want to go through all the
inventory just to find a specific piece (there Is no way to disable It on
mobiles actually)

Thanks for reading
Happy holidays!

Saludos desde México! 🫂
