### ISSUE TITLE
moreblocks_slap_pinewood_2 = unknown Block

### ISSUE THREAD

**Issue by tchncs** [minetest-mods/moreblocks#21]
moreblocks_slap_pinewood_2 and moretrees:stair_acacia_planks are unknown Blocks on our servers.
Its also not craft- or givable.
dont sure which blocks also - this are the only unknown Blocks we found now... .
moreblocks:stair_junglewood_alt_2 does work for example.

**Comment by Calinou** [comment]
In 0.4.13, pinewood was renamed to pine_wood.

**Comment by tchncs** [comment]
Your mod and Minetest and minetest_game are on the latest commit.
I saw, it happens by ```stair_pinewood_alt_2``` also.

**Comment by sofar** [comment]
@Calinou can't we just alias these blocks for him to solve this?

**Comment by sofar** [comment]
I'm deciding not to fix this issue. If someone submits a PR, that's fine, and we can merge it.
