### ISSUE TITLE
attepting nil value while trying to use the chainsaw

### ISSUE THREAD

**Issue by tchncs** [minetest-mods/moreblocks#23]
one of our players tryed to use the chainsaw with some >more<-blocks but it didnt worked.
the result was a nil value -> servercrash.

**Comment by sofar** [comment]
Likely a bug in technic, not moreblocks.

Without a server lua crash trace, this is unfixable. Try again and post the error messages.

**Comment by sofar** [comment]
Looking at technic/tools/chainsaw.lua, it has a hardcoded list of blocks that it knows how to saw.

Moreblocks is not one of them.

I tried, in-game, and could not reproduce this.
