### ISSUE TITLE
notabug repo gone

### ISSUE THREAD

**Issue by asl97** [minetest-mods/moreblocks#27]
https://notabug.org/Calinou/moreblocks lead to 404

**Comment by sofar** [comment]
@asl97 I can't find links to that page, do you really care? Is something still referrring to that URL?

**Comment by asl97** [comment]
@sofar it was in the description in this repo, web archive doesn't have that page archive

google has it but would probably get deleted in the future, https://webcache.googleusercontent.com/search?q=cache:Cmtr4GRx5NEJ:https://github.com/Calinou/moreblocks/+&cd=1&hl=en&ct=clnk&gl=sg
