### ISSUE TITLE
Slab obsidian glass transperency problem

### ISSUE THREAD

**Issue by Fixer-007** [minetest-mods/moreblocks#32]
Slab obsidian glass looks different, when looking through it from opposite sides. From one side it is ok, from another it is transperent without borders.

Examples: https://imgur.com/a/myQjU (correct view below). Screenshots from "Liberty Land" server.

@RealBadAngel suggested that "glasslike framed should be used for such things", source: http://irc.minetest.ru/minetest-dev/2016-02-14#i_4533652

**Comment by sofar** [comment]
Could this be related to https://github.com/minetest/minetest/commit/47464c9344a1a4817ad6e4c6ec44526df305b1f6

?

**Comment by Fixer-007** [comment]
>Could this be related to minetest/minetest@47464c9

no, this appears before your changes on stable 0.4.13

**Comment by Fixer-007** [comment]
Looks like it also affects usual obsidian glass, and probably stairs, for some reason it draws like connected glass while I have it disabled in my config.

**Comment by sofar** [comment]
I have a relatively simple fix, thanks to Kilbith.

**Comment by sofar** [comment]
f92a938d7590e68c2a34d45866a52aa09d6c8fd6
