### ISSUE TITLE
 obsidian glass slabs invisible from one side.

### ISSUE THREAD

**Issue by NathanSalapat** [minetest-mods/moreblocks#34]
Obsidian glass slabs are invisible from one side, while appearing perfectly normal from the other.

**Comment by sofar** [comment]
Is this a duplicate of https://github.com/minetest-mods/moreblocks/issues/32 ? Note, there is a fix for that issue...

**Comment by NathanSalapat** [comment]
I'm not sure, created the issue for sokomine as he requested. Never saw the problem or looked into it. Sounds like it could be a simple as a flipped normal.

**Comment by sofar** [comment]
Already fixed by f92a938d7590e68c2a34d45866a52aa09d6c8fd6
