### ISSUE TITLE
Aliases Causing Warnings in Log

### ISSUE THREAD

**Issue by octacian** [minetest-mods/moreblocks#45]
For some reason a bunch of warnings about the aliases (I assume from Moreblocks) is shown in debug.txt. They go something like this:

```
WARNING[Main]: Not registering alias, item with same name is already defined: stairs:stair_stone -> moreblocks:stair_stone
```

And something like 50 of them.

**Comment by sofar** [comment]
You can safely ignore these. It's a bit verbose, yes.

**Comment by ENDev15** [comment]
Yes, they can be ignored, but it is very annoying when trying to debug other mods etc... Is it possible to add an if statement to check if the conflicting mod (stairs?) is installed and not run the code if true? I took a look at doing this myself, but didn't figure out where.

**Comment by kilbith** [comment]
I agree it's annoying when you're keeping an eye on the console to debug shit. These aliases are sticking there for years and I don't think they're still necessary.

**Comment by jhcole** [comment]
I think b5bf6d6a1c5ceb436642ec1cbe735f7f1bdb8375 should fix the issue. At least it did for me. Is anyone willing to test?

**Comment by sofar** [comment]
@fozolo care to submit a PR?

**Comment by jhcole** [comment]
Sure

**Comment by sofar** [comment]
@jhcole, are you @fozolo?

**Comment by jhcole** [comment]
Yes, I am both of them. Sorry if that is confusing.
