### ISSUE TITLE
Proper release?

### ISSUE THREAD

**Issue by SnarkBoojum** [minetest-mods/moreblocks#50]
Hi,

could you tag a moreblocks release? I just took over the maintenance of the minetest-mod-moreblocks package in Debian, and the last package is from a git commit in 2013... I'd prefer working on a developer-approved git commit rather than a random one!

Thanks,

Snark on #debian-games

**Comment by SnarkBoojum** [comment]
Can I ping you again about it?

Thanks,

Snark on #debian-games

**Comment by Calinou** [comment]
Sorry about the long delay, I'm going to tag version 1.0.0 of More Blocks, More Ores and Map Tools very soon. I will also keep a changelog from now on.

**Comment by Calinou** [comment]
Done: https://github.com/minetest-mods/moreblocks/releases/tag/v1.0.0

A changelog is now being kept from now on, according to the [Keep a Changelog](http://keepachangelog.com/en/0.3.0/) specification.
