### ISSUE TITLE
Super glow glass causing lighting problems?

### ISSUE THREAD

**Issue by Fixer-007** [minetest-mods/moreblocks#55]
Copy pasting it there from https://github.com/minetest/minetest/issues/3964.

>In davisonio/craig-server_game#76 @RHRhino has shown that this lighting bug seems to be caused by super glow glass from the moreblocks mod.
>Super glow glass uses light_source = 15 (https://github.com/davisonio/craig-server_game/blob/master/mods/moreblocks/nodes.lua#L287) when the maximum recommended in the minetest docs is 14 (http://dev.minetest.net/minetest.register_node).
>I think the bug we have here is that when you set light_source to more than 14 it causes the light to stay there permenantly even when you've removed the node.

**super_glow_glass** and **trap_super_glow_glass** are affected by this.

Link: https://github.com/davisonio/craig-server_game/issues/76

**Comment by dora71** [comment]
After today's update of the main minetest program, I couldn't start minetest server because of the mentioned items above.
After setting light_source to 14, I can start the server again.
Please fix nodes.lua

**Comment by sofar** [comment]
https://github.com/minetest-mods/moreblocks/pull/56
