### ISSUE TITLE
Item "moreblocks:slab_pinewood" not defined

### ISSUE THREAD

**Issue by Megaf** [minetest-mods/moreblocks#57]
Missing alias.

**Comment by VanessaE** [comment]
Is this still a problem?  By now, any worlds that had the old pine wood nods will have replaced them.

**Comment by Megaf** [comment]
@VanessaE Will check today and will come back to you as soon as I do so.

**Comment by Calinou** [comment]
Is this still happening with the latest Minetest version?

**Comment by fluxionary** [comment]
i don't even understand what the problem here was, and no further information was provided, i think this issue should be closed.

**Comment by Calinou** [comment]
Closing due to lack of response from OP. This is likely resolved by now, but please comment if you can still reproduce this on the latest More Blocks version.
