### ISSUE TITLE
stairsplus: Pollution of global namespace.

### ISSUE THREAD

**Issue by beyondlimits** [minetest-mods/moreblocks#64]
Stairsplus mod leaks its register functions to global namespace. Shouldn't they be in `moreblocks` namespace instead?

```
register_micro
register_panel
register_slab
register_slope
register_stair
register_stair_slab_panel_micro
```

**Comment by Calinou** [comment]
This should have been fixed by https://github.com/minetest-mods/moreblocks/commit/e622c692e14ab06d4c3744da5d4100fa8a789274, which is included in 1.3.0.
