### ISSUE TITLE
New blocks from default not supported in saw

### ISSUE THREAD

**Issue by Fixer-007** [minetest-mods/moreblocks#66]
Unsupported blocks from 0.4.15:
default:stone_block
default:desert_stone_block
default:obsidian_block
default:sandstone_block
default:coral_skeleton
default:coral_brown - not sure about those, they are decaying to skeleton
default:coral_orange - not sure about those, they are decaying to skeleton

Also, will be nice to have farming:straw sawable.

**Comment by VanessaE** [comment]
https://github.com/minetest-mods/moreblocks/pull/69
