### ISSUE TITLE
Alias More Blocks's tar and its Stairs+ nodes to building_blocks's tar

### ISSUE THREAD

**Issue by Calinou** [minetest-mods/moreblocks#68]
When the `building_blocks` mod is installed, alias More Blocks's tar and its Stairs+ nodes to building_blocks's tar.

**Comment by VanessaE** [comment]
Turns out this has to be done partially inside of building_blocks.  I've submitted a PR for Moreblocks to add the necessary code to build a shapes list that other mods can reference.

**Comment by fozolo** [comment]
This appears to be resolved by minetest-mods/homedecor_modpack@14697ef71b447180bfbd66f311036d53f5606ac6 and minetest-mods/homedecor_modpack@5efa9af1b7055a0073ce8f69cddce64ae793f235. I suggest closing this issue.
