### ISSUE TITLE
Translations buggy

### ISSUE THREAD

**Issue by sigzegv** [minetest-mods/moreblocks#76]
I'm using lastest translations-mod version, and in the game every item with accented character in translation just displays "invalid UTF-8 string".
This is related to using old interface instead of po files, I tried one translation with po system and this works fine.

**Comment by Calinou** [comment]
I'm OK with switching to .po files if it's well-supported. Feel free to send a pull request :)

**Comment by codexp** [comment]
@sigzegv the reason is that it is not a valid UTF-8 string!
French locale is encoded with latin-1 not UTF-8.
I will convert it to UTF-8 while refactoring it to po format.

**Comment by codexp** [comment]
PR #121 will fix this issue.
