### ISSUE TITLE
Please release a new version

### ISSUE THREAD

**Issue by SnarkBoojum** [minetest-mods/moreblocks#83]
The current release of moreblocks isn't compatible with the current release of the homedecor modpack (since it doesn't provide shapes_list, for instance) : could you tag a new release, please?

Thanks!

**Comment by Jat15** [comment]
@SnarkBoojum create block "Terracotta Shingle", "Wood Shingles", "Ashphalt Shingle" in homedecor for add in moreblocks ?

**Comment by SnarkBoojum** [comment]
@Jat15 sorry, I don't understand your sentence

**Comment by Jat15** [comment]
@SnarkBoojum  Are you talking about shape for roofs?

**Comment by SnarkBoojum** [comment]
No, I'm talking about the variable shapes_list, which has been added to moreblocks after the last release and which is used by the latest homedecor ; see commit e9c6cef4dd6090b561c55268114c832cd0ccfe0e.

**Comment by Calinou** [comment]
I just tagged [v1.1.0](https://github.com/minetest-mods/moreblocks/releases/tag/v1.1.0).

If there are any issues, let me know :)
